theme: jekyll-theme-minimal
title: Desktop Goose's Resource Hub
description: An unofficial place to share your mods, etc. PRs and stars are appreciated!
logo: https://camo.githubusercontent.com/961a86566650a2628f92fc87ad2b3b73a6dd7b27/68747470733a2f2f692e696d6775722e636f6d2f694537424835552e706e67
show_downloads: false
google_analytics: UA-157579039-1
